### ISSUE TITLE
Is there a video record of this tutorial?

### ISSUE THREAD

**Issue by huanranchen** [sayakpaul/robustness-foundation-models#2]
Hi~ I'm very interested in this tutorial but I have not registered for neurips 2022... Would you share the record of this tutorial to youtube or some other social media?

**Comment by sayakpaul** [comment]
We will likely do this once we have obtained the necessary permissions. 

Keep an eye out here in the repo.

**Comment by huanranchen** [comment]
Neurips has release this tutorial~ I can't wait to watch this!
https://slideslive.com/38992786

**Comment by sayakpaul** [comment]
Thanks! We have updated our repository too.
